# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Lint and Unittests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python env
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are linting errors
        flake8 .
    - name: Check isort
      run: |
        # stop when there are unsorted imports
        isort . --check-only
    - name: Check black
      run: |
        # stop when there are unformatted files
        black . --check
    - name: GEE authentification
      env:
        EARTHENGINE_TOKEN: ${{ secrets.EARTHENGINE_TOKEN }}
      run: |
        python .github/gee_token.py
    - name: Test with unittest
      run: |
        python -m unittest discover -s ./tests -p '*.py'